### ISSUE TITLE
want to add the background color for the contact form

### ISSUE THREAD

**Issue by saurabhsingh720** [amupedia2021/Project-Amupedia#418] opened 2023-06-14 15:52 UTC
### Description

![con](https://github.com/amupedia2021/Project-Amupedia/assets/106748434/17387b74-e6cf-4acc-bc59-47c4d7e24568)
want to add the background color for the contact form

### Current behaviour

no any background color
![hj](https://github.com/amupedia2021/Project-Amupedia/assets/106748434/47a8ce51-4249-4b2d-a3cb-936a81242344)

### Expected behaviour

want to change the background color to beige
![con](https://github.com/amupedia2021/Project-Amupedia/assets/106748434/f1335996-5cb6-4bf9-94c5-918221fce780)

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

![DESCRIPTION](LINK.png)  

### OS

Windows

### Are you contributing for a program ?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by Dimple-01** [comment] 2023-06-15 12:53
I want to work on this.
Please assign this work to me.
I will fix this in few hours.

**Comment by Sandeep77942** [comment] 2023-06-21 20:57
If the issue is still open, I would like to work on it under Gssoc'23.

**Comment by saurabhsingh720** [comment] 2023-06-23 10:22
@amupedia2021
please assign this task under GSSOC'23

**Comment by mandliyarajendra11** [comment] 2023-07-15 05:16
no need someone already working on design

**Closed by mandliyarajendra11** 2023-07-15 05:16 UTC
Labels: bug, gssoc23
