### ISSUE TITLE
🐞 [BUG] - navbar not responsive 

### ISSUE THREAD

**Issue by laibaahsan27** [amupedia2021/Project-Amupedia#339] opened 2023-05-30 20:51 UTC
### Description

The Nav bar is not reponsive for a particular width .

### Current behaviour

the home button is going out of the frame and the spacing is off.

![image](https://github.com/amupedia2021/Project-Amupedia/assets/123810454/4884f2de-3d44-4af5-87ad-c0725184ffc7)

### Expected behaviour

i will make it responsive.
please assign it to me.

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

![DESCRIPTION](LINK.png)  

### Browsers

Chrome

### OS

Windows

### Are you contributing for a program ?

GSSoC2023

### Code of Conduct

- [x] I have read and agree to the Contributing Guidelines of this project.

**Comment by Michelle031** [comment] 2023-05-31 05:36
Can I be assigned this issue

**Comment by tusharbansal22** [comment] 2023-05-31 07:50
@laibaahsan27 , will you have a different navbar for tablet view or will just adjust to fit the home button somehow?

**Comment by laibaahsan27** [comment] 2023-05-31 21:47
@tusharbansal22 i will adjust the existing one

**Comment by laibaahsan27** [comment] 2023-06-01 09:39
@anmode assign it to me please

**Comment by Sandeep77942** [comment] 2023-06-21 21:00
If the issue is still open, I would like to work on it under Gssoc'23.

**Closed** 2023-07-14 07:07 UTC
Labels: bug, gssoc23
