### ISSUE TITLE
[Bug]: Update the copyright section

### ISSUE THREAD

**Issue by abhinav-m22** [amupedia2021/Project-Amupedia#235] opened 2023-05-25 15:15 UTC
### Give a brief about the bug discovered✍

In the copyright section of the web page, the year 2021 is hard-coded.
It is not the standard way of writing code.
Everytime the code will have to be changed for updating the year.
Also, the section is not aligned properly.

<img width="213" alt="image" src="https://github.com/amupedia2021/Project-Amupedia/assets/113239388/c9a62b03-672e-48a8-811b-59b147845952">

### What is the expected behavior?

The web page needs to have a footer with a function that fetches the dynamic value of the current year.
The alignment need to be fixed with the CSS.

### Give a brief description to get the expect behaviour.

Add a function to dynamically fetch the year from a function which is the best practice to add the copyright to any website to make it look formal.

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/amupedia2021/Project-Amupedia/blob/master/CONTRIBUTING.md) of this project.

**Comment by kinsteve** [comment] 2023-05-25 19:24
To get the expected behavior I will fetch the current year using 
new Date().getFullYear() , than changing the html of copyright using span tag and textContent property.

And to perfectly align it , I will have look into its css defined using #ftbg id , I will apply margin:auto to align it horizontaly and align-item : center for vertical alignment.

No I am not A contributor of GSSoC2023 , but Please assign me this issue.

**Comment by anmode** [comment] 2023-05-25 23:34
@kinsteve If @abhinav-m22 agree I'll assign this to you! IF he wanna continue then please could you look at other issues

**Comment by abhinav-m22** [comment] 2023-05-26 06:06
@kinstev Please find another issue.. Because I've already started working on this issue

**Comment by tusharbansal22** [comment] 2023-05-26 07:35
But isn't the year in copyright meant to be the year of start of the project @anmode , why do we want it to be the current year?

**Comment by AmanJain18** [comment] 2023-05-27 07:33
> @kinstev Please find another issue.. Because I've already started working on this issue

Have u implemented ?

**Comment by abhinav-m22** [comment] 2023-05-29 05:43
Someone already resolved the issue

**Comment by AmanJain18** [comment] 2023-05-29 06:05
Okay, No problem, 😊 Find and work on another issue..

**Comment by AmanJain18** [comment] 2023-05-29 06:06
Remarks: The issue is already fixed..

**Closed** 2023-05-29 06:05 UTC
Labels: bug, good first issue, GSSoC2023
