### ISSUE TITLE
🐞 [BUG] - Footer Fix

### ISSUE THREAD

**Issue by anmode** [amupedia2021/Project-Amupedia#280] opened 2023-05-27 14:22 UTC
### Description

Just look at production side

### Current behaviour

null

### Expected behaviour

null

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Browsers

Chrome

### OS

Mac

### Are you contributing for a program ?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the [CONTRIBUTING GUIDELINES](https://github.com/amupedia2021/Project-Amupedia/blob/master/CONTRIBUTING.md) of this project.

**Comment by kailashchoudhary11** [comment] 2023-05-27 15:03
@anmode You mean the social links? I would like to work on it.

**Comment by anmode** [comment] 2023-05-27 16:17
yess. i think it has gone wrong anything... they were present before..

**Comment by Vraj1103** [comment] 2023-05-27 18:26
@anmode I would like to work on footer under gssoc'23 badge.

**Comment by anmode** [comment] 2023-05-28 02:31
yeah! there is gssoc level

**Comment by kailashchoudhary11** [comment] 2023-05-28 02:52
> yeah! there is gssoc badge

@anmode You can assign this to someone else. I know the issue is due to the background image. But I am not much good at CSS.

**Comment by debsouryadatta** [comment] 2023-05-28 09:17
I can work on this issue, can you please assign it me @anmode

**Comment by Vraj1103** [comment] 2023-05-28 13:59
@anmode I've got quite a good experience as a UI/Frontend developer, can you please assign me the above mentioned task?

**Comment by AmanJain18** [comment] 2023-05-29 18:06
Issue got fixed by some one...Look for other issue...

**Closed by AmanJain18** 2023-05-29 18:06 UTC
Labels: bug, help wanted, GSSoC2023, Issue by Mentors
