### ISSUE TITLE
Add search bar in Contributors section

### ISSUE THREAD

**Issue by akanksha984** [amupedia2021/Project-Amupedia#498] opened 2023-07-12 17:45 UTC
### Is your feature request related to a problem ? Please describe. ✍️

I would like to add search bar features to find the contributors.
Please assign it to me under gssoc'23

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Step 1
2. Step 2
3. Step 3
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by Harshil-Jani** [comment] 2023-07-12 17:59
Duplicate of https://github.com/amupedia2021/Project-Amupedia/issues/468

**Closed by Harshil-Jani** 2023-07-12 17:59 UTC
Labels: enhancement, gssoc23
