### ISSUE TITLE
🐞 [BUG] - Need to be fixed the line on contact us section...

### ISSUE THREAD

**Issue by Brijesh1963** [amupedia2021/Project-Amupedia#524] opened 2023-07-14 16:29 UTC
### Description

 Need to be fixed the line on contact us section...
Its overlayed with another boxes,give some gap between them....

![responsiveness8](https://github.com/amupedia2021/Project-Amupedia/assets/98037970/1d68d8a6-5f70-47ba-9672-f0159d6405c9)

### Current behaviour

The boxes overlayed another box on contact us section...

### Expected behaviour

Its should be need fixed for mobile devices....

### Reproduction steps

```bash
see on contact us section...
```

### Screenshots

![DESCRIPTION](LINK.png)  

### Are you contributing for a program ?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by Harshil-Jani** [comment] 2023-07-14 21:38
Duplicate of https://github.com/amupedia2021/Project-Amupedia/pull/514

**Closed** 2023-07-14 21:39 UTC
Labels: bug, gssoc23
