### ISSUE TITLE
Improper spacing in mobile view

### ISSUE THREAD

**Issue by akanksha984** [amupedia2021/Project-Amupedia#516] opened 2023-07-14 08:20 UTC
### Description

![image](https://github.com/amupedia2021/Project-Amupedia/assets/97845909/a21f86c7-c53f-4acc-9d43-138d83e90912)

I would like to fix this error, The contact us form spacing is not appropriate. Please assign it to me under gssoc'23

### Current behaviour

Spacing issue

### Expected behaviour

Proper spacing

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

![DESCRIPTION](LINK.png)  

### Are you contributing for a program ?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by Harshil-Jani** [comment] 2023-07-14 11:35
Duplicate of https://github.com/amupedia2021/Project-Amupedia/issues/513

**Closed by Harshil-Jani** 2023-07-14 11:35 UTC
Labels: bug, gssoc23
