### ISSUE TITLE
Increasing the visibility of branch name 

### ISSUE THREAD

**Issue by SonamMalik17** [amupedia2021/Project-Amupedia#82] opened 2023-05-20 13:49 UTC
The name of the various displayed over the picture are not visible clearly , I wish to add some more styling to make it look better.

**Comment by amrit2611** [comment] 2023-05-20 15:07
I have visited the website and know what the issue is and how to exactly solve it.
Would love to work on this issue.
Kindly assign this to me under the GSSOC '23

**Comment by naveeng2402** [comment] 2023-05-20 17:02
I'm interested too

**Comment by tusharbansal22** [comment] 2023-05-26 16:07
@SonamMalik17  , please follow the issue template and reopen

**Closed by tusharbansal22** 2023-05-26 16:07 UTC
